//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CT_PHIEUNHAP()
        {
            this.SANPHAM = new HashSet<SANPHAM>();
        }
    
        public int MACTPN { get; set; }
        public int MAPN { get; set; }
        public string MALOAI { get; set; }
        public int SOLUONG { get; set; }
        public double GIA { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAM { get; set; }
    }
}
