//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TANGKEM
    {
        public int MACTKM { get; set; }
        public string MASPTK { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual CT_KHUYENMAI CT_KHUYENMAI { get; set; }
        public virtual SANPHAMTANGKEM SANPHAMTANGKEM { get; set; }
    }
}
