//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int MAKH { get; set; }
        public string MALOAI { get; set; }
        public int SOLUONG { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
