//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MAHD { get; set; }
        public int MAPM { get; set; }
        public System.DateTime NGAY { get; set; }
        public double THANHTIEN { get; set; }
        public string MASOTHUE { get; set; }
    
        public virtual PHIEUMUA PHIEUMUA { get; set; }
    }
}
