//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAISANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAISANPHAM()
        {
            this.CT_KHUYENMAI = new HashSet<CT_KHUYENMAI>();
            this.CT_PHIEUDAT = new HashSet<CT_PHIEUDAT>();
            this.CT_PHIEUNHAP = new HashSet<CT_PHIEUNHAP>();
            this.DANHGIA = new HashSet<DANHGIA>();
        }
    
        public string MALOAI { get; set; }
        public string TENLOAI { get; set; }
        public double GIA { get; set; }
        public int TRANGTHAI { get; set; }
        public string HINHANH { get; set; }
        public string MOTA { get; set; }
        public int LOAI { get; set; }
        public string MATH { get; set; }
        public string MANCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_KHUYENMAI> CT_KHUYENMAI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUDAT> CT_PHIEUDAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUNHAP> CT_PHIEUNHAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANHGIA> DANHGIA { get; set; }
        public virtual THUONGHIEU THUONGHIEU { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
