//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUDAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUDAT()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUTRAs = new HashSet<PHIEUTRA>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public int MAPD { get; set; }
        public System.DateTime NGAYDAT { get; set; }
        public string HO { get; set; }
        public string TEN { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
        public System.DateTime NGAYGIAO { get; set; }
        public int TRANGTHAI { get; set; }
        public Nullable<int> MANVD { get; set; }
        public Nullable<int> MANVGH { get; set; }
        public int MAKH { get; set; }
        public Nullable<int> MAQUAN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual NHANVIEN NHANVIEN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUTRA> PHIEUTRAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
        public virtual QUAN QUAN { get; set; }
    }
}
