//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUTRACH
    {
        public int MAPHUTRACH { get; set; }
        public int MANV { get; set; }
        public int MAQUAN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual QUAN QUAN { get; set; }
    }
}
