//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanXeMay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public int MASP { get; set; }
        public string SOKHUNG { get; set; }
        public string SOMAY { get; set; }
        public Nullable<int> MAPD { get; set; }
        public Nullable<int> MAPT { get; set; }
        public int MACTPN { get; set; }
        public double GIA { get; set; }
    
        public virtual CT_PHIEUNHAP CT_PHIEUNHAP { get; set; }
        public virtual PHIEUDAT PHIEUDAT { get; set; }
        public virtual PHIEUTRA PHIEUTRA { get; set; }
    }
}
